server:
  address: 'localhost'
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  liquibase:
    change-log: changelog.yaml
    enabled: true
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
