INSERT INTO "USERS" ("USERNAME", "PASSWORD") VALUES ('Charlie Scene', 'Gdy7wQ');
INSERT INTO "USERS" ("USERNAME", "PASSWORD") VALUES ('J-Dog', 'o8eQfF');
INSERT INTO "USERS" ("USERNAME", "PASSWORD") VALUES ('Funny Man', 'YxeO22');
INSERT INTO "USERS" ("USERNAME", "PASSWORD") VALUES ('Johnny 3 Tears', 'D5hVnE');
INSERT INTO "USERS" ("USERNAME", "PASSWORD") VALUES ('Danny', 'tqLyZ1');
